apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - pod.yaml
  # - job.yaml

# generatorOptions:
#   disableNameSuffixHash: true

# configMapGenerator:
# - name: tokenizer
#   files:
#   - tokenizer.json
#   - tokenizer_config.json
